### ISSUE TITLE
luaharfbuzz breaks tostring

### ISSUE THREAD

**Issue by deepakjois** [harfbuzz/luaharfbuzz#49]
Email from Simon Dales:

```
When testing I spotted an issue with
tostring().

"Receives a value of any type and converts it to a string in a
human-readable format"[1].


///////////

Run:
//////////////////
for k,v in pairs(luaharfbuzz) do
  print(k,v)
end
//////////////////
Should only fail if your lua, say texlua, hasn't got luaharfbuzz. Else
it should list the elements of the table.

I have a more sophisticated version of this loop that does it
recursively. So your code breaks a recursive list of _G.

//////
I did a couple of versions of the same hack: remove __tostring. Either
subsequently in lua or by commenting out in the sources.

Then the above lua works as the lua manual says it should.

But this breaks the use of tostring in some of your lua code, that
expects the returned string to be an internal value, such as language's
4 letter code.

//////////
2 obvious solutions:
* rename the function, but this probably breaks existing lua code
* fix the __tostring so that it works as the default class behaviour.

Any other better ones?

//////////////////////

[1] https://www.lua.org/manual/5.3/manual.html#pdf-tostring

//////////////////////

Simon
```

**Comment by deepakjois** [comment]
Fixed by #57?

**Comment by khaledhosny** [comment]
Still an issue, but I don’t really understand what is going on. The error messages don’t even make any sense:
```
bad argument #1 to '?' (harfbuzz.Feature expected, got harfbuzz.Feature)
```

It is basically complaining that it got the thing it was expecting!

Someone who actually understands Lua needs to debug this.

**Comment by pgundlach** [comment]
I hate to admit it, but I asked my favourite AI for a fix and an explanation. 

```
diff --git a/src/class_utils.c b/src/class_utils.c
index 750ad4f..cc3a464 100644
--- a/src/class_utils.c
+++ b/src/class_utils.c
@@ -15,13 +15,17 @@ int register_class(lua_State *L, const char *name, const luaL_Reg *methods, cons
   }
 
   luaL_setfuncs(L, methods, 0);
-  lua_pop(L, 1);
 
   lua_newtable(L);
   luaL_setfuncs(L, functions, 0);
 
-  luaL_getmetatable(L, name);
+  /* The class table only needs access to the instance metatable for constants;
+     keep its own metatable light to avoid triggering instance metamethods. */
+  lua_newtable(L);
+  lua_pushvalue(L, -3);
+  lua_setfield(L, -2, "__index");
   lua_setmetatable(L, -2);
+
+  lua_remove(L, -2);
   return 1;
 }
-
```

Here’s what happened and why class_utils.c needed those tweaks:

The core bug: The “class tables” (e.g. harfbuzz.Tag, harfbuzz.Direction) were given the same metatable as instances. That metatable carries metamethods like __tostring and __eq that assume a userdata payload. When you iterate pairs(luaharfbuzz) and then print(k, v), Lua tries to stringify those tables via __tostring, hits luaL_checkudata, and errors (“harfbuzz.Direction expected, got harfbuzz.Direction”). Same problem broke constructors (e.g. Tag.new became nil) after the first change because the stack cleanup was off.

What the change does:

The class table now gets its own lightweight metatable whose __index points at the instance metatable. This still exposes constants defined on the instance metatable but prevents the class table from inheriting instance-only metamethods like __tostring/__eq.
Stack cleanup is corrected with lua_remove so the metatables aren’t left in the wrong place.
Effect: Class tables are safe to print/inspect, constructors stay callable, and you can still access constants. The pairs(luaharfbuzz)/print loop no longer crashes because the class tables no longer trigger userdata-only metamethods.

I will prepare a pull request. All tests pass.

My test file:

```lua
package.cpath = "build/lib/lua/5.4/?.so;" .. package.cpath

local harfbuzz = require("luaharfbuzz")
local harfbuzzsubset = require("luaharfbuzzsubset")

print("Harfbuzz Subset API version", harfbuzzsubset.version())


for k,v in pairs(harfbuzz) do
  print(k,v)
end



for k,v in pairs(harfbuzzsubset) do
  print(k,v)
end
```
